mode: required
method: legacy

labels:
    step: "CPU"

items:
    - id: intel
      packages: []
      name: "Intel"
      description: "Intel CPU."

    - id: amd
      packages: []
      name: "AMD"
      description: "AMD CPU."

    - id: pi
      packages: []
      name: "Raspberry Pi"
      description: "Raspberry Pi (ARM) board."

    - id: none
      packages: []
      name: "None of these"
      description: "Fall back to enabling all hardware support instead of a specific CPU."
