mode: required
method: legacy

labels:
    step: "Theme"

default: nyubones

items:
    - id: nyubones
      packages: []
      name: "Nyubones"
      description: "Warm, low-contrast dark theme."

    - id: eumyangu
      packages: []
      name: "Eumyangu"
      description: "Alternate GTK theme."
