modules-search: [local, @out@/lib/calamares/modules]

instances:
- id: internet-help
  module: notesqml
  config: notesqml-internet-help.conf
- id: forms
  module: packagechooser
  config: packagechooser-forms.conf
- id: theme
  module: packagechooser
  config: packagechooser-theme.conf
- id: filesystem
  module: packagechooser
  config: packagechooser-filesystem.conf
- id: disk
  module: packagechooser
  config: packagechooser-disk.conf
- id: cpu
  module: packagechooser
  config: packagechooser-cpu.conf
- id: gpu
  module: packagechooser
  config: packagechooser-gpu.conf

sequence:
- show:
  - notesqml@internet-help
  - welcome
  - locale
  - keyboard
  - packagechooser@disk
  - packagechooser@filesystem
  - packagechooser@cpu
  - packagechooser@gpu
  - users
  - packagechooser@forms
  - packagechooser@theme
- exec:
  - collect-secrets
  - nixos-config-generate
  - nixos-config-install
- show:
  - finished

branding: carbon

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: false
quit-at-end: false
