defaultGroups:
    - users
    - networkmanager
    - wheel

setRootPassword: false
doReusePassword: false
doAutologin: false

passwordRequirements:
    minLength: 8
    maxLength: 64

allowWeakPasswords: true
allowWeakPasswordsDefault: false

user:
  shell: /run/current-system/sw/bin/zsh
  forbidden_names: [ root ]

hostname:
  location: etc
  writeHostsFile: false
  forbidden_names: [ localhost ]
